# Generated by Django 5.0.4 on 2024-04-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('passc', models.CharField(max_length=15)),
                ('ad', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
