# Generated by Django 5.0.4 on 2024-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_savefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefile',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
