# Generated by Django 5.0.4 on 2024-04-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0003_alter_savefile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='cont',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='savefile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
