# Generated by Django 5.0.4 on 2024-04-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0004_reg_cont_alter_savefile_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regs',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('passc', models.CharField(max_length=15)),
                ('cont', models.CharField(max_length=20)),
                ('ad', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
