# Generated by Django 5.0.4 on 2024-04-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0005_regs_delete_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regs',
            new_name='Reg',
        ),
    ]
